// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tp.proto

package tp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Posts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Posts) Reset()         { *m = Posts{} }
func (m *Posts) String() string { return proto.CompactTextString(m) }
func (*Posts) ProtoMessage()    {}
func (*Posts) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9fca5410d86c429, []int{0}
}

func (m *Posts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Posts.Unmarshal(m, b)
}
func (m *Posts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Posts.Marshal(b, m, deterministic)
}
func (m *Posts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Posts.Merge(m, src)
}
func (m *Posts) XXX_Size() int {
	return xxx_messageInfo_Posts.Size(m)
}
func (m *Posts) XXX_DiscardUnknown() {
	xxx_messageInfo_Posts.DiscardUnknown(m)
}

var xxx_messageInfo_Posts proto.InternalMessageInfo

func (m *Posts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Post struct {
	NotifyComment        string   `protobuf:"bytes,1,opt,name=notifyComment,proto3" json:"notifyComment,omitempty"`
	NotifyTime           string   `protobuf:"bytes,2,opt,name=notifyTime,proto3" json:"notifyTime,omitempty"`
	PostcardTitle        string   `protobuf:"bytes,3,opt,name=postcardTitle,proto3" json:"postcardTitle,omitempty"`
	PostcardDescription  string   `protobuf:"bytes,4,opt,name=postcardDescription,proto3" json:"postcardDescription,omitempty"`
	PostcardPicksNumber  string   `protobuf:"bytes,5,opt,name=postcardPicksNumber,proto3" json:"postcardPicksNumber,omitempty"`
	PostcardPvNumber     string   `protobuf:"bytes,6,opt,name=postcardPvNumber,proto3" json:"postcardPvNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9fca5410d86c429, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetNotifyComment() string {
	if m != nil {
		return m.NotifyComment
	}
	return ""
}

func (m *Post) GetNotifyTime() string {
	if m != nil {
		return m.NotifyTime
	}
	return ""
}

func (m *Post) GetPostcardTitle() string {
	if m != nil {
		return m.PostcardTitle
	}
	return ""
}

func (m *Post) GetPostcardDescription() string {
	if m != nil {
		return m.PostcardDescription
	}
	return ""
}

func (m *Post) GetPostcardPicksNumber() string {
	if m != nil {
		return m.PostcardPicksNumber
	}
	return ""
}

func (m *Post) GetPostcardPvNumber() string {
	if m != nil {
		return m.PostcardPvNumber
	}
	return ""
}

type PostRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9fca5410d86c429, []int{2}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Posts)(nil), "tp.Posts")
	proto.RegisterType((*Post)(nil), "tp.Post")
	proto.RegisterType((*PostRequest)(nil), "tp.PostRequest")
}

func init() { proto.RegisterFile("tp.proto", fileDescriptor_b9fca5410d86c429) }

var fileDescriptor_b9fca5410d86c429 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x69, 0xb7, 0x8e, 0xf6, 0x1b, 0x43, 0x89, 0x97, 0xe0, 0x61, 0x8c, 0x22, 0x3a, 0x3c,
	0x14, 0xd9, 0x7e, 0x82, 0x82, 0x37, 0x19, 0xb3, 0x7f, 0xc0, 0xc5, 0x4f, 0x08, 0x9a, 0x26, 0x26,
	0x5f, 0x0b, 0x5e, 0xfd, 0xe5, 0x92, 0xc4, 0x96, 0x16, 0xbd, 0x25, 0xcf, 0xfb, 0x7c, 0xef, 0xe1,
	0x85, 0x9c, 0x4c, 0x65, 0xac, 0x26, 0xcd, 0x52, 0x32, 0xe5, 0x0d, 0x64, 0x07, 0xed, 0xc8, 0xb1,
	0x35, 0x64, 0xc6, 0x3f, 0x78, 0xb2, 0x99, 0x6d, 0x97, 0xbb, 0xbc, 0x22, 0x53, 0xf9, 0xe4, 0x18,
	0x71, 0xf9, 0x9d, 0xc2, 0xdc, 0xff, 0xd9, 0x15, 0xac, 0x1a, 0x4d, 0xf2, 0xed, 0xeb, 0x5e, 0x2b,
	0x85, 0x0d, 0xf1, 0x64, 0x93, 0x6c, 0x8b, 0xe3, 0x14, 0xb2, 0x35, 0x40, 0x04, 0xb5, 0x54, 0xc8,
	0xd3, 0xa0, 0x8c, 0x88, 0x6f, 0xf1, 0xbd, 0xe2, 0xc5, 0xbe, 0xd6, 0x92, 0x3e, 0x90, 0xcf, 0x62,
	0xcb, 0x04, 0xb2, 0x3b, 0xb8, 0xe8, 0xc1, 0x03, 0x3a, 0x61, 0xa5, 0x21, 0xa9, 0x1b, 0x3e, 0x0f,
	0xee, 0x7f, 0xd1, 0xf8, 0xe2, 0x20, 0xc5, 0xbb, 0x7b, 0x6a, 0xd5, 0x09, 0x2d, 0xcf, 0xa6, 0x17,
	0xa3, 0x88, 0xdd, 0xc2, 0xf9, 0x80, 0xbb, 0x5f, 0x7d, 0x11, 0xf4, 0x3f, 0xbc, 0x5c, 0xc1, 0x32,
	0x6c, 0x82, 0x9f, 0x2d, 0x3a, 0xda, 0xed, 0xa1, 0xa8, 0xcd, 0x33, 0xda, 0x4e, 0x0a, 0x64, 0xd7,
	0x90, 0x3f, 0x22, 0xc5, 0x31, 0xcf, 0x86, 0xf5, 0xa2, 0x79, 0x59, 0xf4, 0xc0, 0x9d, 0x16, 0x61,
	0xfc, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xd5, 0xcf, 0xa5, 0x88, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TpServiceClient is the client API for TpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TpServiceClient interface {
	GetPosts(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Posts, error)
}

type tpServiceClient struct {
	cc *grpc.ClientConn
}

func NewTpServiceClient(cc *grpc.ClientConn) TpServiceClient {
	return &tpServiceClient{cc}
}

func (c *tpServiceClient) GetPosts(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Posts, error) {
	out := new(Posts)
	err := c.cc.Invoke(ctx, "/tp.TpService/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TpServiceServer is the server API for TpService service.
type TpServiceServer interface {
	GetPosts(context.Context, *PostRequest) (*Posts, error)
}

func RegisterTpServiceServer(s *grpc.Server, srv TpServiceServer) {
	s.RegisterService(&_TpService_serviceDesc, srv)
}

func _TpService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tp.TpService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpServiceServer).GetPosts(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tp.TpService",
	HandlerType: (*TpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPosts",
			Handler:    _TpService_GetPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tp.proto",
}
