version: "2"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/public
    ports:
      - 80:80
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cm_db
      - MYSQL_USER=cm_user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
